// resources/js/components/Content/CatalogComponents/CatalogMainComponent.jsx
import React from 'react';
import CatalogProductsListComponent from "./CatalogProductsListComponent";
import classes from "./CatalogMainComponent.module.scss";
import CatalogSorterBlockComponent from "../../UI/Selects/CatalogSorterBlockComponent";

const CatalogMainComponent = ({setCatalogMobileActive}) => {


    return (
        <div className={classes.catalogMain}>
            <CatalogSorterBlockComponent setCatalogMobileActive={setCatalogMobileActive}/>
            <CatalogProductsListComponent/>
        </div>
    );
};

export default CatalogMainComponent;

// resources/js/components/Content/CatalogComponents/CatalogMainComponent.vue
<template>
    <div :class="$style.catalogMain">
        <CatalogSorterBlockComponent/>
<!--        <CatalogSorterBlockComponent setCatalogMobileActive={setCatalogMobileActive}/>
            <CatalogProductsListComponent/>-->
    </div>
</template>
<style module>
@import "CatalogMainComponent.module.scss";
</style>
<script setup>
import CatalogSorterBlockComponent from "../../UI/Selects/CatalogSorterBlockComponent.vue";
</script>
