// resources/js/components/Content/CatalogComponents/CatalogProductsListComponent.vue
<template>
    <div :class="$style.productList">
        <ProductCardComponent v-for="product in products" :product="product"/>
    </div>
    <div ref="childRef" :style=" (isRequesting || fullProductLoaded) ? 'display: none' : null"/>
</template>
<script setup>
import ProductCardComponent from "../Product/ProductCardComponent.vue";
import {computed, onMounted, ref, watch} from "vue";
import {useRoute} from "vue-router";
import useScroll from "../../../hooks/useScroll.js";

const route = useRoute();
const category = computed(() => route.params.category)
const queryParams = computed(() => route.query);
const products = ref([]);
const page = ref(1);
const isRequesting = ref(true);
const firstProductLoaded = ref(false);
const fullProductLoaded = ref(false);
const childRef = ref(null);

onMounted(() => {
    useScroll(document.body, childRef.value, getProducts);
})

watch([category, queryParams], async ([newCategory, newQueryParams]) => {
    if (newCategory) {
        isRequesting.value = true;
        axios.get(`/api/catalog/${newCategory + getInitQueryParams(newQueryParams)}`).then((response) => {
            products.value = response.data;
            page.value = 2;
            firstProductLoaded.value = true;
            fullProductLoaded.value = false;
        })
            .catch((response) => {
                console.log(response);
            })
            .finally(() => {
                isRequesting.value = false;
            })
    }
}, {immediate: true})

function getProducts() {
    if (firstProductLoaded.value) {
        isRequesting.value = true;
        axios.get(`/api/catalog/${category.value + getQueryParams()}`).then((response) => {
            if (!response.data.length) {
                fullProductLoaded.value = true;
                return;
            }
            products.value.push(...response.data);
            ++page.value;
        })
            .catch((response) => {
                console.log(response);
            })
            .finally(() => {
                isRequesting.value = false;
            })
    }
}

function getInitQueryParams(queryParams) {
    const initQueryParams = new URLSearchParams({...queryParams, page: 1})
    return '?' + initQueryParams.toString();
}

function getQueryParams() {
    const resultQueryParams = new URLSearchParams({...queryParams.value, page: page.value})
    return '?' + resultQueryParams.toString();
}
</script>

<style module>
@import "CatalogProductsListComponent.module.css";
</style>

// resources/js/components/Content/CatalogComponents/CatalogProductsListComponent.jsx
import {useEffect, useMemo, useRef, useState} from 'react';
import ProductCardComponent from "../Product/ProductCardComponent";
import classes from "./CatalogProductsListComponent.module.css";
import axios from "axios";
import {useParams, useSearchParams} from "react-router-dom";
import useScroll from "../../../hooks/useScroll";
import {isEmpty} from "lodash";

const CatalogProductsListComponent = () => {
    const [products, setProducts] = useState([]);
    const [page, setPage] = useState(1);
    const {category} = useParams();
    const [searchParams, setSearchParams] = useSearchParams();
    const childRef = useRef();
    const intersection = useScroll(document.body, childRef, getProducts);
    const [isRequesting, setIsRequesting] = useState(true);
    const [fullProductLoaded, setFullProductLoaded] = useState(false);
    const [firstProductLoaded, setFirstProductLoaded] = useState(false);
    const ProductList = useMemo(() => {
        return (
            products.map((product) =>
                <ProductCardComponent key={product.id} product={product}/>
            )
        )
    }, [products])

    function getProducts() {
        if (firstProductLoaded) {
            setIsRequesting(true)
            axios.get(`/api/catalog/${category}${getSearchParams()}`).then((response) => {
                if (isEmpty(response.data)) {
                    setFullProductLoaded(true);
                    return;
                }
                setProducts([...products, ...response.data]);
                setPage(page => page + 1);
            })
                .catch((response) => {
                    console.log(response);
                })
                .finally(() => {
                    setIsRequesting(false);
                })
        }
    }

    useEffect(() => {
        axios.get(`/api/catalog/${category}${getInitSearchParams()}`).then((response) => {
            setProducts(response.data);
            setPage(2);
            setFirstProductLoaded(true);
            setFullProductLoaded(false)
        })
            .catch((response) => {
                console.log(response);
            })
            .finally(() => {
                setIsRequesting(false);
            })
    }, [category, searchParams]);

    function getSearchParams() {
        const paramsString = searchParams.toString() ? searchParams.toString() + `&page=${page}` : `page=${page}`;
        return `?${paramsString}`;
    }

    function getInitSearchParams() {
        const paramsString = searchParams.toString() ? searchParams.toString() + `&page=1` : `page=1`;
        return `?${paramsString}`;
    }

    return (
        <div className={classes.productList}>
            {
                ProductList
            }
            <div ref={childRef} style={(isRequesting || fullProductLoaded) ? {display: 'none'} : null}/>
        </div>
    );
};

export default CatalogProductsListComponent;
