// resources/js/components/Header/HeaderComponent.jsx
import React, {useState} from 'react';
import classes from "./HeaderComponent.module.scss";
import {Link} from "react-router-dom";
import InputHeaderSearchComponent from "../UI/Inputs/InputHeaderSearchComponent";
import PopupAuthenticationComponent from "../Popups/PopupAuthenticationComponent";
import PopupCatalogComponent from "../Popups/PopupCatalogComponent";
import {useDispatch, useSelector} from "react-redux";
import logoImg from "../../../img/logo.png"
import PopupSearchMobileComponent from "../Popups/PopupSearchMobileComponent";
import {HiMenu, HiSearch} from "react-icons/hi";
import {FaUser} from "react-icons/fa";
import {RiShoppingCartFill} from "react-icons/ri";
import {isEmpty} from "lodash";
import {changeCategoryPopupState} from "../../store/reducers/catalogReducer";
import {changeAuthNPopupState} from "../../store/reducers/userReducer";


const HeaderComponent = () => {
    const [isAuth, email, basketQuantity] = useSelector((state) => [state.userReducer.isAuth, state.userReducer.userEmail, state.basketReducer.basketProductQuantity]);
    const dispatch = useDispatch();
    const [searchPopupState, setSearchPopupState] = useState(false);

    return (
        <header className={classes.header}>
            <div className={classes.container}>
                <div className={classes.topHeader}>top</div>
                <div className={classes.bodyHeader}>
                    <div className={classes.headerNavMenu}>
                        <HiMenu className={classes.burger} onClick={() => dispatch(changeCategoryPopupState(true))}/>
                        <Link to="/" className={classes.headerNavMenuLogo}>
                            <img src={logoImg}
                                 alt="Логотип"/>
                        </Link>
                        <div className={classes.headerActionsMobile}>
                            <div className={classes.actionMobileItem} onClick={() => setSearchPopupState(true)}>
                                <HiSearch className={classes.actionMobileIcon}/>
                            </div>
                        </div>
                    </div>
                    <InputHeaderSearchComponent containerPropClass={classes.headerSearch}>Поиск
                        товаров</InputHeaderSearchComponent>
                    <div className={classes.headerActions}>
                        {
                            isAuth ?
                                <Link className={classes.headerActionItem} to={"/profile"}>
                                    <FaUser className={classes.headerActionItemIcon}/>
                                    <div
                                        className={classes.headerActionItemText}>{isEmpty(email) ? "Ошибка" : email} </div>
                                </Link>
                                :
                                <div className={classes.headerActionItem}
                                     onClick={() => dispatch(changeAuthNPopupState(true))}>
                                    <FaUser className={classes.headerActionItemIcon}/>
                                    <div className={classes.headerActionItemText}>{isAuth ? email : "Войти"} </div>
                                </div>
                        }

                        <Link to={"/cart"} className={classes.headerActionItem}>
                            <div className={classes.basketIconContainer}>
                                <RiShoppingCartFill className={classes.headerActionItemIcon}/>
                                {
                                    basketQuantity
                                        ? <span className={classes.basketQuantity}>{basketQuantity}</span>
                                        : null
                                }
                            </div>
                            <span className={classes.headerActionItemText}>Корзина</span>
                        </Link>
                    </div>
                </div>
            </div>
            <PopupCatalogComponent/>
            {!isAuth && <PopupAuthenticationComponent/>}
            <PopupSearchMobileComponent active={searchPopupState} setActive={setSearchPopupState}/>
        </header>
    );
};

export default HeaderComponent;

// resources/js/components/Header/HeaderComponent.vue
<template>
    <header :class="$style.header">
        <div :class="$style.container">
            <!--            <div :class="$style.topHeader">top</div>-->
            <div :class="$style.bodyHeader">
                <div :class="$style.headerNavMenu">
                    <font-awesome-icon :class="$style.burger" icon="fa-solid fa-bars"
                                       @click="changeCatalogPopupState(true)"/>
                    <router-link :to="{name: 'home'}" :class="$style.headerNavMenuLogo">
                        <img src="../../../img/logo.png"
                             alt="Логотип"/>
                    </router-link>
                    <div :class="$style.headerActionsMobile">
                        <font-awesome-icon :class="$style.actionMobileIcon" icon="fa-solid fa-magnifying-glass"
                                           @click="changeSearchPopupState(true)"/>
                    </div>
                </div>
                <InputHeaderSearchComponent placeholder="Поиск" :containerPropClass="$style.headerSearch"/>
                <div :class="$style.headerActions">
                    <router-link :to="{name: 'profile-home'}" v-if="isAuth" :class="$style.headerActionItem" >
                        <font-awesome-icon icon="fa-solid fa-user" :class="$style.headerActionItemIcon"/>
                        <div
                            :class="$style.headerActionItemText">Кабинет
                        </div>
                    </router-link>
                    <div v-else :class="$style.headerActionItem" @click="changeAuthPopupState(true)">
                        <font-awesome-icon icon="fa-solid fa-user" :class="$style.headerActionItemIcon"/>
                        <div :class="$style.headerActionItemText">Войти</div>
                    </div>

                    <router-link :to="{name: 'basket'}" :class="$style.headerActionItem">
                        <div :class="$style.basketIconContainer">
                            <font-awesome-icon icon="fa-solid fa-cart-shopping" :class="$style.headerActionItemIcon"/>
                            <span v-if="basketQuantity" :class="$style.basketQuantity">{{ basketQuantity }}</span>
                        </div>
                        <span :class="$style.headerActionItemText">Корзина</span>
                    </router-link>
                </div>
            </div>
        </div>
        <PopupCatalogComponent/>
        <PopupAuthenticationComponent/>
        <!--<PopupSearchMobileComponent active={searchPopupState} setActive={setSearchPopupState}/>-->
    </header>
</template>


<script setup>

import InputHeaderSearchComponent from "../UI/Inputs/InputHeaderSearchComponent.vue";
import PopupCatalogComponent from "../Popups/PopupCatalogComponent.vue";
import PopupAuthenticationComponent from "../Popups/PopupAuthenticationComponent.vue";
import {useStore} from "vuex";
import {computed, ref} from "vue";

const store = useStore();
const searchPopupState = ref(false)
const isAuth = computed(() => store.state.user.isAuth)
const basketQuantity = computed(() => store.getters.basketProductQuantity)


function changeAuthPopupState(state) {
    store.dispatch('changeAuthPopupState', state);
}

function changeSearchPopupState(state) {
    searchPopupState.value = state;
}

function changeCatalogPopupState(state) {
    store.dispatch('changeCatalogPopupState', state);
}
</script>

<style module>
@import "HeaderComponent.module.scss";
</style>
