// resources/js/components/UI/ShowMoreOrLess/ShowMoreOrLessProductDescriptionComponent.vue
<template>
    <div :class="$style.wrapper" v-bind="$attrs">
        <div :class="[$style.title, titleClass]">{{ title }}</div>
        <div :class="bodyClasses">
            <slot/>
        </div>
        <a @click="link ? null : openOrClose()" :class="[$style.button, buttonClass]">
            {{ link ? "Подробнее" : state ? "Свернуть" : "Развернуть" }}</a>
    </div>
</template>

<script setup>

import {computed, ref, useCssModule} from "vue";

const props = defineProps({
    title: {required: false},
    titleClass: {required: false},
    bodyClass: {required: false},
    buttonClass: {required: false},
    link: {required: false, default: false}
})

const state = ref(false);
const style = useCssModule();
const bodyClasses = computed(() => {
    if (state.value) {
        return [style.body, style.open]
    }
    return style.body;
})

function openOrClose() {
    state.value = !state.value;
}
</script>

<style module>
@import "ShowMoreOrLessProductDescriptionComponent.module.scss";
</style>

// resources/js/components/UI/ShowMoreOrLess/ShowMoreOrLessProductDescriptionComponent.jsx
import React, {useState} from 'react';
import classes from "./ShowMoreOrLessProductDescriptionComponent.module.scss"

const ShowMoreOrLessProductDescriptionComponent = ({title = null, wrapperClass = null, titleClass = null, bodyClass = null, buttonClass = null,
                                                       children = "Текст", link = false}) => {

    const [bodyClasses, setBodyClasses] = useState([classes.body, bodyClass])

    function openOrClose(event){
        event.preventDefault();

        if(!bodyClasses.find((item) => item === classes.open)){
            setBodyClasses([...bodyClasses, classes.open]);
        }
        else {
            setBodyClasses(bodyClasses.filter((item) => item !== classes.open));
        }
    }

    return (

        <div className={[classes.wrapper, wrapperClass].join(" ")}>
            <div className={[classes.title, titleClass].join(" ")}>{title}</div>
            <div className={bodyClasses.join(" ")}>
                {children}
            </div>
            <a onClick={link ? null : (event) => openOrClose(event)} className={[classes.button, buttonClass].join(" ")}>{link ? "Подробнее" : bodyClasses.find((item) => item === classes.open) ? "Свернуть" : "Развернуть" }</a>
        </div>
    );
};

export default ShowMoreOrLessProductDescriptionComponent;
