// resources/js/components/UI/Raiting/StarsRatingComponent.jsx
import React, {useState} from 'react';
import StarComponent from "./StarComponent";

const StarsRatingComponent = ({maxStars = 5, startRating = 0, readOnly = false, cursorPointer = false}) => {

    const [rating, setRating] = useState({value: startRating, valueHover: null});

    function setRatingFn(value) {
        if (readOnly) return;
        setRating({...rating, value: value });
    }

    function setHoverFn(value) {
        if (readOnly) return;
        setRating({...rating, valueHover: value });
    }

    return (
        <div style={{display: "flex"}}>
            {[...Array(maxStars)].map((star, index) => {
                const value = index + 1;
                return (
                    <StarComponent
                        cursorPointer={cursorPointer}
                        num={value}
                        key={index}
                        setValue={setRatingFn}
                        value={rating.value}
                        setHover={setHoverFn}
                        hover={rating.valueHover}
                    />
                );
            })}
        </div>
    );
};

export default StarsRatingComponent;

// resources/js/components/UI/Raiting/StarsRatingComponent.vue
<template>
    <div :style="{display: 'flex'}">
        <template v-for="(star, i) in maxStars" :key="(i + 1)">
            <font-awesome-icon v-if="(i + 1) <= (rating.valueHover || rating.value)" icon="fa-solid fa-star"
                               @click="setValue(i + 1)" @mouseenter="setHover(i + 1)"
                               @mouseleave="setHover(null)"
                               :style="{color: starColor, cursor: canEdit && 'pointer'}"

            />
            <font-awesome-icon v-else icon="fa-regular fa-star"
                               @click="setValue(i + 1)" @mouseenter="setHover(i + 1)"
                               @mouseleave="setHover(null)"
                               :style="{color: starColor, cursor: canEdit && 'pointer'}"
            />
        </template>
    </div>
</template>

<script setup>
import {reactive} from "vue";

const props = defineProps({
    maxStars: {default: 5},
    startRating: {default: 0},
    canEdit: {default: false},
    starColor: {default: '#000000'}
})

const rating = reactive({value: props.startRating, valueHover: null});

function setValue(value) {
    if (props.canEdit) {
        rating.value = value
    }
}

function setHover(value) {
    if (props.canEdit) {
        rating.valueHover = value;
    }
}

</script>
