// resources/js/components/UI/Spoiler/SpoilerComponent.vue
<template>
    <div :class="classesWrapper" v-bind="$attrs">
        <div :class="[$style.title, classTitle]" @click="changeStatusSpoiler">
            <slot name="title"/>
            <font-awesome-icon icon="fa-solid fa-angle-down" :class="$style.titleIcon"/>
        </div>
        <div :class="[$style.body, classBody]">
            <slot name="body"/>
        </div>
    </div>
</template>

<script setup>
import {computed, ref, useCssModule} from "vue";

const props = defineProps({
    classTitle: [String, Array],
    classBody: [String, Array],
})

const spoilerStatus = ref(true);
const style = useCssModule();
const classesWrapper = computed(() => {
    if (spoilerStatus.value) {
        return style.spoiler;
    }
    return [style.spoiler, style.close];
})

function changeStatusSpoiler() {
    spoilerStatus.value = !spoilerStatus.value;
}
</script>

<style module>
@import "SpoilerComponent.module.scss";
</style>

// resources/js/components/UI/Spoiler/SpoilerComponent.jsx
import React, {useEffect, useMemo, useState} from 'react';
import classes from "./SpoilerComponent.module.scss";
import {IoIosArrowDown} from "react-icons/io";

const SpoilerComponent = ({classWrapper, classTitle, classBody, title, children, defaultStatus = true}) => {


    const [spoilerStatus, setSpoilerStatus] = useState(defaultStatus);
    const classesWrapper = useMemo(() => {
        if (!spoilerStatus) {
            return [classes.spoiler, classWrapper, classes.close];
        }
        return [classes.spoiler, classWrapper];
    }, [spoilerStatus])

    function changeStatusSpoiler() {
        setSpoilerStatus(status => !status)
    }

    return (
        <div className={classesWrapper.join(" ")}>
            <div className={[classes.title, classTitle].join(" ")} onClick={changeStatusSpoiler}>
                {title}
                <IoIosArrowDown className={classes.titleIcon}/>
            </div>
            <div className={[classes.body, classBody].join(" ")}>
                {children}
            </div>
        </div>
    );
};

export default SpoilerComponent;
