// resources/js/Pages/BasketPage.jsx
import React from 'react';
import classes from "./BasketPage.module.scss";
import ButtonComponent from "../components/UI/Buttons/ButtonComponent";
import LikeComponent from "../components/UI/LikeComponent/LikeComponent";
import CounterComponent from "../components/UI/Counter/CounterComponent";
import {FiTrash} from "react-icons/fi";
import {LazyLoadImage} from "react-lazy-load-image-component";
import useBasketDeleteItem from "../hooks/BasketHooks/useBasketDeleteItem";
import {useSelector} from "react-redux";

const BasketPage = () => {
    const basket = useSelector((state) => state.basketReducer);
    const basketDeleteItem = useBasketDeleteItem();
    const products = basket.basketItems;
    const basketPrice = basket.basketFullPrice;
    const basketQuantity = basket.basketProductQuantity;


    return (
        <div className={classes.basket}>
            <div className={classes.content}>
                <div className={classes.basketHeader}>
                    Корзина {basketQuantity}
                </div>
                <div className={classes.basketBody}>
                    {
                        products.map(product =>
                            <div className={classes.basketItem} key={product.id}>
                                <div className={classes.basketItemImage}>
                                    <LazyLoadImage src={product?.frontImage}/>
                                </div>
                                <div className={classes.basketItemMainBlock}>
                                    <div className={classes.basketItemInfo}>
                                        <div className={classes.basketItemTitle}>
                                            {product.title}

                                        </div>
                                        <div className={classes.basketItemPrices}>
                                            <div className={classes.basketItemPriceNew}>
                                                {product.price * product.quantity}
                                            </div>
                                            <div className={classes.basketItemPriceOld}>
                                                {product.price}
                                            </div>
                                        </div>
                                    </div>
                                    <div className={classes.basketItemActions}>
                                        <div className={classes.basketItemActionsRight}>
                                            <LikeComponent propClass={classes.basketItemActionIcon}/>
                                            <FiTrash className={classes.basketItemActionIcon}
                                                     onClick={() => basketDeleteItem(product)}/>
                                        </div>
                                        <div className={classes.basketItemActionsLeft}>
                                            <CounterComponent product={product} initialQuantity={product.quantity}/>
                                        </div>
                                    </div>
                                </div>
                            </div>)
                    }
                </div>
            </div>
            <div className={classes.basketASideContainer}>
                <div className={classes.basketASide}>
                    <ButtonComponent classWrapper={classes.orderButton}>Оформить заказ</ButtonComponent>
                    <div className={classes.basketASideInfo}>
                        <div className={classes.mainCalculateBlock}><span>Итого</span><span>{basketPrice} ₽</span></div>
                        <div className={classes.defaultCalculateBlock}><span>Товары </span><span>100000 ₽</span></div>
                        <div className={classes.discountCalculateBlock}><span>Скидка </span><span>11000 ₽</span></div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default BasketPage;

// resources/js/Pages/BasketPage.vue
<template>
    <div :class="$style.basket">
        <div :class="$style.content">
            <div :class="$style.basketHeader">
                Корзина {{ basketProductQuantity }}
            </div>
            <div :class="$style.basketBody">
                <div v-for="product in basketProducts" :class="$style.basketItem" :key="product.id">
                    <div :class="$style.basketItemImage">
                        <img :src="product?.frontImage" loading="lazy" alt="Товар">
                    </div>
                    <div :class="$style.basketItemMainBlock">
                        <div :class="$style.basketItemInfo">
                            <div :class="$style.basketItemTitle">
                                {{ product.title }}

                            </div>
                            <div :class="$style.basketItemPrices">
                                <div :class="$style.basketItemPriceNew">
                                    {{ product.price * product.quantity }}
                                </div>
                                <div :class="$style.basketItemPriceOld">
                                    {{ product.price }}
                                </div>
                            </div>
                        </div>
                        <div :class="$style.basketItemActions">
                            <div :class="$style.basketItemActionsRight">
                                <LikeComponent :prop-class="$style.basketItemActionIcon"/>
                                <font-awesome-icon icon="fa-solid fa-trash" :class="$style.basketItemActionIcon"
                                                   @click="basketDeleteProduct(product.id)"/>
                            </div>
                            <div :class="$style.basketItemActionsLeft">
                                <CounterComponent :product="product" :initial-quantity="product.quantity"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div :class="$style.basketASideContainer">
            <div :class="$style.basketASide">
                <ButtonComponent :class="$style.orderButton">Оформить заказ</ButtonComponent>
                <div :class="$style.basketASideInfo">
                    <div :class="$style.mainCalculateBlock"><span>Итого</span><span>{{ basketFullPrice }} ₽</span></div>
                    <div :class="$style.defaultCalculateBlock"><span>Товары </span><span>100000 ₽</span></div>
                    <div :class="$style.discountCalculateBlock"><span>Скидка </span><span>11000 ₽</span></div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import ButtonComponent from "../components/UI/Buttons/ButtonComponent.vue";
import {useStore} from "vuex";
import {computed} from "vue";
import useBasketRemoveProduct from "../hooks/BasketHooks/useBasketRemoveProduct.js";
import CounterComponent from "../components/UI/Counter/CounterComponent.vue";
import LikeComponent from "../components/UI/LikeComponent/LikeComponent.vue";
import useBasketProductReload from "../hooks/BasketHooks/useBasketProductReload.js";

const store = useStore();
const basketProducts = computed(() => store.state.basket.basketProducts);
const basketFullPrice = computed(() => store.getters.basketFullPrice);
const basketProductQuantity = computed(() => store.getters.basketProductQuantity);
const basketDeleteProduct = useBasketRemoveProduct();
const reloadBasket = useBasketProductReload();
reloadBasket();

</script>

<style module>
@import "BasketPage.module.scss";
</style>
