// resources/js/Pages/CatalogPageComponent.vue
<template>
    <div :class="$style.app">
        <div :class="$style.catalogTitle">
            <div :class="$style.catalogTitleText">
                {{ category }}
            </div>
            <div :class="$style.catalogProductCount">
                0 товаров
            </div>
        </div>
        <div :class="$style.catalogBody">
            <FilterComponent :class="catalogFilterClasses"
                             :set-catalog-mobile-active="catalogMobileActive"
                             :catalog-mobile-active="setCatalogMobileActive"/>
            <CatalogMainComponent :set-catalog-mobile-active="setCatalogMobileActive"/>
        </div>
    </div>
</template>
<script setup>

import {computed, ref, useCssModule} from "vue";
import {useRoute} from "vue-router";
import CatalogMainComponent from "../components/Content/CatalogComponents/CatalogMainComponent.vue";
import FilterComponent from "../components/Content/CatalogComponents/Filter/FilterComponent.vue";

const route = useRoute()
const category = computed(() => route.params.category);
const catalogMobileActive = ref(false);
const style = useCssModule();
const catalogFilterClasses = computed(() => {
    if (catalogMobileActive.value) {
        return [style.catalogFilter, style.mobile];
    }
    return [style.catalogFilter];
})

function setCatalogMobileActive() {
    catalogMobileActive.value = !catalogMobileActive.value
}
</script>
<style module>
@import "CatalogPageComponent.module.scss";

</style>

// resources/js/Pages/CatalogPageComponent.jsx
import React, {useEffect, useMemo, useState} from 'react';
import classes from "./CatalogPageComponent.module.scss";
import FilterComponent from "../components/Content/CatalogComponents/Filter/FilterComponent";
import CatalogMainComponent from "../components/Content/CatalogComponents/CatalogMainComponent";
import {useParams} from "react-router-dom";

const CatalogPageComponent = () => {
    const [catalogMobileActive, setCatalogMobileActive] = useState(false);
    const {category} = useParams();
    const catalogFilterClasses = useMemo(() => {
        if (catalogMobileActive) {
            return [classes.catalogFilter, classes.mobile];
        }
        return [classes.catalogFilter];
    }, [catalogMobileActive])

    return (
        <div className={classes.app}>
            <div className={classes.catalogTitle}>
                <div className={classes.catalogTitleText}>
                    {category}
                </div>
                <div className={classes.catalogProductCount}>
                    123131231 товаров
                </div>
            </div>
            <div className={classes.catalogBody}>
                <FilterComponent classProp={catalogFilterClasses.join(" ")}
                                 CatalogMobileActive={catalogMobileActive}
                                 setCatalogMobileActive={setCatalogMobileActive}
                />
                <CatalogMainComponent setCatalogMobileActive={setCatalogMobileActive}/>
            </div>
        </div>
    );
};

export default CatalogPageComponent;
