// resources/js/Pages/ProductPageComponent.vue
<template>
    <div v-if="product" :class="$style.productPage">
        <div :class="$style.productContent">
            <div :class="$style.productHeader">
                <div :class="$style.productTitle">
                    {{ product.title }}
                </div>
                <div :class="$style.productActions">
                    <ul :class="$style.list">
                        <li :class="$style.item">
                            <StarsRatingComponent start-rating="4"/>
                        </li>
                        <li :class="$style.item"><span :class="$style.link">Коментарии</span></li>
                        <!-- переход на блок с коментариями -->
                    </ul>
                </div>
            </div>
            <div :class="$style.swiperWrapper">
                <SwiperProductPageComponent :images="product.images" :class-main-slide="$style.slide"
                                            :class-main-wrapper="$style.mainSlider" :class-nav-slide="$style.slide"
                                            :class-nav-wrapper="$style.navSlider"/>
            </div>
            <div :class="$style.productShortInfo">
                                <ShowMoreOrLessProductDescriptionComponent :title-class="$style.descriptionShortTitle"
                                                                           title="Описание"
                                                                           :class="$style.descriptionShort" :link="true">
                                    {{ product.description }}
                                </ShowMoreOrLessProductDescriptionComponent>
                <ShowMoreOrLessProductCharacteristicsComponent :title-class="$style.characteristicsShortTitle"
                                                               title="Характеристики"
                                                               :wrapper-class="$style.characteristicsShort"
                                                               :link="true"/>
            </div>
            <div :class="$style.aSideBlock">
                <div :class="$style.productASide">
                    <div :class="$style.productPrices">
                        <div :class="$style.productPriceLower">
                            {{ product.price }} ₽
                        </div>
                        <div :class="$style.productPriceOld">
                            {{ product.price }} ₽
                        </div>
                    </div>
                    <ButtonComponent :class="$style.button" @click="addItemToBasket(productId)">В корзину
                    </ButtonComponent>
                </div>
            </div>
        </div>
        <div :class="$style.productMain">
            <div :class="$style.productInfo">
                <ShowMoreOrLessProductCharacteristicsComponent title="Характеристики"
                                                               :title-class="$style.characteristicsTitle"/>
                                    <div>
                                        <ShowMoreOrLessProductDescriptionComponent title="Описание"
                                                                                   :title-class="$style.descriptionTitle">
                                            {{ product.description }}
                                        </ShowMoreOrLessProductDescriptionComponent>
                                    </div>
            </div>
        </div>
        <div :class="$style.mobileOrderBlock">
            <div :class="$style.productPrices">
                <div :class="$style.productPriceLower">{{ product.price }} ₽</div>
                <div :class="$style.productPriceOld">{{ product.price }} ₽</div>
            </div>
            <ButtonComponent :class="$style.button" @click="addItemToBasket(productId)">В корзину</ButtonComponent>
        </div>
        <div :class="$style.userActivityAndRating">
            <div :class="$style.userActivityBlock">
                <div :class="$style.userActivityHeader">
                    <div :class="[$style.headerTitle, userActivityContent && $style.headerTitleActive]"
                         @click="() => userActivityContent = true">
                        Отзывы
                    </div>
                    <div :class="[$style.headerTitle, !userActivityContent && $style.headerTitleActive]"
                         @click="() => userActivityContent = false">Вопросы
                    </div>
                </div>
                <div :class="$style.userActivityBody">
                    <ProductCommentComponent v-if="userActivityContent"/>
                    <template v-else>
                        <ProductCommentComponent/>
                        <ProductCommentComponent/>
                        <ProductCommentComponent/>
                    </template>
                </div>
            </div>
            <ProductRatingComponent :class="$style.rating"/>
        </div>
    </div>
</template>

<script setup>


import {computed, ref, watchEffect} from "vue";
import {useRoute} from "vue-router";
import useBasketAddItem from "../hooks/BasketHooks/useBasketAddItem.js";
import StarsRatingComponent from "../components/UI/Raiting/StarsRatingComponent.vue";
import ButtonComponent from "../components/UI/Buttons/ButtonComponent.vue";
import ProductRatingComponent from "../components/Content/Product/ProductRatingComponent.vue";
import ProductCommentComponent from "../components/Content/Product/ProductCommentComponent.vue";
import SwiperProductPageComponent from "../components/Sliders/SwiperProductPageComponent.vue";
import ShowMoreOrLessProductCharacteristicsComponent
    from "../components/UI/ShowMoreOrLess/ShowMoreOrLessProductCharacteristicsComponent.vue";
import ShowMoreOrLessProductDescriptionComponent
    from "../components/UI/ShowMoreOrLess/ShowMoreOrLessProductDescriptionComponent.vue";

const route = useRoute();
const productId = computed(() => route.params.productId);
const product = ref();
const addItemToBasket = useBasketAddItem();
const userActivityContent = ref(true);


watchEffect(async () => {
    try {
        if (productId.value) {
            const response = await axios.get(`/api/product/${productId.value}`);
            product.value = response.data;
        }
    } catch (error) {
        console.log(error);
    }
});
</script>

<style module>
@import "ProductPageComponent.module.scss";
</style>

// resources/js/Pages/ProductPageComponent.jsx
import React, {useEffect, useState} from 'react';
import classes from "./ProductPageComponent.module.scss";
import {Link, useParams} from "react-router-dom";
import StarsRatingComponent from "../components/UI/Raiting/StarsRatingComponent.vue";
import ShowMoreOrLessProductDescriptionComponent
    from "../components/UI/ShowMoreOrLess/ShowMoreOrLessProductDescriptionComponent";
import ShowMoreOrLessProductCharacteristicsComponent
    from "../components/UI/ShowMoreOrLess/ShowMoreOrLessProductCharacteristicsComponent";
import ButtonComponent from "../components/UI/Buttons/ButtonComponent.vue";
import SwiperAdvertisementProductsComponent from "../components/Sliders/SwiperAdvertisementProductsComponent";
import SwiperProductPageComponent from "../components/Sliders/SwiperProductPageComponent";
import ProductRatingComponent from "../components/Content/Product/ProductRatingComponent";
import ProductCommentComponent from "../components/Content/Product/ProductCommentComponent";
import axios from "axios";
import useBasketAddItem from "../hooks/BasketHooks/useBasketAddItem";

const ProductPageComponent = () => {
    const [userActivityContent, setUserActivityContent] = useState(true);
    const {productId} = useParams();
    const addItemToBasket = useBasketAddItem()
    const [product, setProduct] = useState({});

    useEffect(() => {
        axios.get(`/api/product/${productId}`)
            .then((response) => {
                setProduct(response.data);
            })
            .catch((response) => {
                console.log(response.data);
            })
    }, [productId]);


    return (
        <div className={classes.productPage}>
            <div className={classes.productContent}>
                <div className={classes.productHeader}>
                    <div className={classes.productTitle}>
                        {product.title}
                    </div>
                    <div className={classes.productActions}>
                        <ul className={classes.list}>
                            <li className={classes.item}><StarsRatingComponent
                                maxStars={5} readOnly={true} startRating={4} cursorPointer={true}/></li>
                            <li className={classes.item}><Link className={classes.link}>Коментарии</Link></li>
                        </ul>
                    </div>
                </div>
                <div className={classes.swiperWrapper}>
                    <SwiperProductPageComponent classNavWrapper={classes.navSlider} classNavSlide={classes.slide}
                                                classMainSlide={classes.slide} classMainWrapper={classes.mainSlider}
                                                images={product.images}/>
                </div>
                <div className={classes.productShortInfo}>
                    <ShowMoreOrLessProductDescriptionComponent titleClass={classes.descriptionShortTitle}
                                                               title={"Описание"}
                                                               wrapperClass={classes.descriptionShort} link={true}>
                        {product.description}
                    </ShowMoreOrLessProductDescriptionComponent>
                    <ShowMoreOrLessProductCharacteristicsComponent titleClass={classes.characteristicsShortTitle}
                                                                   title={"Характеристики"}
                                                                   wrapperClass={classes.characteristicsShort}
                                                                   link={true}/>
                </div>
                <div className={classes.aSideBlock}>
                    <div className={classes.productASide}>
                        <div className={classes.productPrices}>
                            <div className={classes.productPriceLower}>
                                21 103 ₽
                            </div>
                            <div className={classes.productPriceOld}>
                                20 s ₽
                            </div>
                        </div>
                        <ButtonComponent classWrapper={classes.button} onClick={() => addItemToBasket(productId)}>В корзину</ButtonComponent>
                    </div>
                </div>
            </div>
            <div className={classes.productMain}>
                <div className={classes.productInfo}>
                    <ShowMoreOrLessProductCharacteristicsComponent title={"Характеристики"}
                                                                   titleClass={classes.characteristicsTitle}/>
                    <div>
                        <ShowMoreOrLessProductDescriptionComponent title={"Описание"}
                                                                   titleClass={classes.descriptionTitle}>
                            {product.description}
                        </ShowMoreOrLessProductDescriptionComponent>
                    </div>
                </div>
                <div>
                    <SwiperAdvertisementProductsComponent title={"Похожее"}/>
                    <SwiperAdvertisementProductsComponent title={"Реклама"}/>
                </div>
            </div>
            <div className={classes.mobileOrderBlock}>
                <div className={classes.productPrices}>
                    <div className={classes.productPriceLower}>21 103 ₽</div>
                    <div className={classes.productPriceOld}>20 103 ₽</div>
                </div>
                <ButtonComponent classWrapper={classes.button} onClick={() => useAddItemToBasket(productId)}>В корзину</ButtonComponent>
            </div>
            <div className={classes.userActivityAndRating}>
                <div className={classes.userActivityBlock}>
                    <div className={classes.userActivityHeader}>
                        <div
                            className={[classes.headerTitle, userActivityContent && classes.headerTitleActive].filter(Boolean).join(" ")}
                            onClick={() => !userActivityContent && setUserActivityContent(true)}>Отзывы
                        </div>
                        <div
                            className={[classes.headerTitle, !userActivityContent && classes.headerTitleActive].filter(Boolean).join(" ")}
                            onClick={() => userActivityContent && setUserActivityContent(false)}>Вопросы
                        </div>
                    </div>
                    <div className={classes.userActivityBody}>
                        {
                            userActivityContent ?
                                <><ProductCommentComponent/></>
                                : <><ProductCommentComponent/><ProductCommentComponent/><ProductCommentComponent/></>
                        }
                    </div>
                </div>
                <ProductRatingComponent classWrapper={classes.rating}/>
            </div>
        </div>
    );
};

export default ProductPageComponent;
