// resources/js/Pages/ProfilePageComponent.jsx
import React, {useEffect, useState} from 'react';
import classes from "./ProfilePageComponent.module.scss";
import {Route, Routes, useNavigate} from "react-router";
import {NavLink} from "react-router-dom";
import ProfileSettingsComponent from "../components/Content/Profile/ProfileSettingsComponent";
import ProfileDesktopHomeComponent from "../components/Content/Profile/ProfileDesktopHomeComponent";
import useSignOut from "../hooks/AuthHooks/useSignOut";

const ProfilePageComponent = () => {
    const navigate = useNavigate();
    const signOut = useSignOut();
    const [profileState, setProfileState] = useState(false);
    const [profileClasses, setProfileClasses] = useState({
        menuProfile: [classes.profileMenu],
        contentProfile: [classes.content, classes.hiddenOnMobile]
    });

    useEffect(() => {
        if (profileState === true) {
            setProfileClasses({
                menuProfile: [profileClasses.menuProfile.filter((item) => item !== classes.hiddenOnMobile), classes.hiddenOnMobile],
                contentProfile: profileClasses.contentProfile.filter((item) => item !== classes.hiddenOnMobile)
            })
        } else {
            setProfileClasses({
                menuProfile: profileClasses.menuProfile.filter((item) => item !== classes.hiddenOnMobile),
                contentProfile: [...profileClasses.contentProfile, classes.hiddenOnMobile]
            })

        }
    }, [profileState]);


    return (
        <div className={classes.profile}>
            <div className={profileClasses.menuProfile.join(" ")}>
                <div className={classes.profileImage}>
                    <img
                        src="https://avatars.mds.yandex.net/i?id=fcd934fb3fd86beedd13a150df698436402c5590-5113868-images-thumbs&n=13"
                        alt=""/>
                </div>
                <div className={classes.menuBlock}>
                    <div className={classes.menuBlockTitle}>
                        Профиль
                    </div>
                    <div className={classes.blockMenuList}>
                        <NavLink to={"/profile"}
                                 className={({isActive}) => [classes.link, classes.menuItem, classes.hiddenOnMobile, isActive ? classes.active : null].filter(Boolean).join(" ")}
                                 end><span
                            className={classes.text}>Главная</span></NavLink>
                        <NavLink to={"settings"}
                                 className={({isActive}) => [classes.link, classes.menuItem, isActive ? classes.active : null].filter(Boolean).join(" ")}><span
                            className={classes.text}>Настройки профиля</span></NavLink>
                        <NavLink to={"/cart"}
                                 className={({isActive}) => [classes.link, classes.menuItem, isActive ? classes.active : null].filter(Boolean).join(" ")}><span
                            className={classes.text}>Корзина</span></NavLink>
                        <div className={classes.menuItem} onClick={() => signOut()}>
                            <span className={classes.text}>Выйти из аккаунта</span>
                        </div>

                    </div>
                </div>
            </div>
            <div className={profileClasses.contentProfile.join(" ")}>
                {
                    profileState && <div className={classes.showOnMobile} onClick={() => navigate(-1)}>
                        Назад
                    </div>
                }
                <Routes>
                    <Route path="settings"
                           element={<ProfileSettingsComponent setProfileState={setProfileState}/>}/>
                    <Route path=""
                           element={<ProfileDesktopHomeComponent/>}/>
                </Routes>
            </div>
        </div>
    );
};

export default ProfilePageComponent;

// resources/js/Pages/ProfilePageComponent.vue
<template>
    <RouteAuthComponent>
        <div :class="$style.profile">
            <div :class="profileClasses.menuProfile">
                <div :class="$style.profileImage">
                    <img
                        src="https://avatars.mds.yandex.net/i?id=fcd934fb3fd86beedd13a150df698436402c5590-5113868-images-thumbs&n=13"
                        alt=""/>
                </div>
                <div :class="$style.menuBlock">
                    <div :class="$style.menuBlockTitle">
                        Профиль
                    </div>
                    <div :class="$style.blockMenuList">
                        <router-link :to="{name: 'profile-home'}"
                                     :class="[$style.link, $style.menuItem, $style.hiddenOnMobile]"
                                     :exact-active-class="$style.active">
                    <span :class="$style.text">
                        Главная
                    </span>
                        </router-link>
                        <router-link :to="{name: 'settings'}" :class="[$style.link, $style.menuItem]"
                                     :active-class="$style.active">
                    <span :class="$style.text">
                        Настройки профиля
                    </span>
                        </router-link>
                        <router-link :to="{name: 'basket'}" :class="[$style.link, $style.menuItem]">
                    <span :class="$style.text">
                        Корзина
                    </span>
                        </router-link>
                        <div :class="$style.menuItem" @click="signOut">
                            <span :class="$style.text">Выйти из аккаунта</span>
                        </div>
                    </div>
                </div>
            </div>
            <div :class="profileClasses.contentProfile">
                <div v-if="profileState" :class="$style.showOnMobile" @click="router.go(-1)">
                    Назад
                </div>
                <router-view :set-profile-state="setProfileState"/>
            </div>
        </div>
    </RouteAuthComponent>
</template>


<script setup>
import {useRouter} from "vue-router";
import useSignOut from "../hooks/AuthHooks/useSignOut.js";
import {computed, ref, useCssModule} from "vue";
import RouteAuthComponent from "../components/Route/RouteAuthComponent.vue";

const router = useRouter();
const signOutHook = useSignOut();
const style = useCssModule();
const profileState = ref(false);
const profileClasses = computed(() => {
    if (profileState.value === true) {
        return {
            menuProfile: [style.profileMenu, style.hiddenOnMobile],
            contentProfile: style.content
        }
    }
    return {
        menuProfile: style.profileMenu,
        contentProfile: [style.content, style.hiddenOnMobile]
    }
});


function setProfileState(state) {
    profileState.value = state;
}
function signOut(){
    router.replace({name: 'home'})
    signOutHook()
}

</script>

<style module>
@import "ProfilePageComponent.module.scss";
</style>
