// resources/js/components/Sliders/SwiperPrevSlideButton.jsx
import React from 'react';
import {useSwiper} from "swiper/react";
import classes from "./SwiperChangeSlideButton.module.scss";
import {IoIosArrowDown} from "react-icons/io";
const SwiperPrevSlideButton = ({buttonClass = null}) => {
    const swiper = useSwiper()

    return (
        <IoIosArrowDown className={[classes.button, buttonClass].join(" ")} onClick={() => swiper.slidePrev()}/>
    );
};

export default SwiperPrevSlideButton;

// resources/js/components/Sliders/SwiperPrevSlideButton.vue
<template>
    <font-awesome-icon icon="fa-solid fa-angle-down" :class="$style.button" @click="swiper.slidePrev()" v-bind="$attrs"/>
</template>

<script setup>
import {useSwiper} from "swiper/vue";

const swiper = useSwiper()
</script>

<style module>
@import "SwiperChangeSlideButton.module.scss";
</style>
