// resources/js/components/Popups/PopupSearchMobileComponent.vue
<template>
    <div :class="popupWrapperClasses" @click="setActive(false)">
        <div :class="$style.body" @click.stop>
            <div :class="$style.backButton" @click="setActive(false)">назад</div>
            <InputHeaderSearchComponent :class="$style.searchContainer"/>
        </div>
    </div>
</template>

<script setup>

import InputHeaderSearchComponent from "../UI/Inputs/InputHeaderSearchComponent.vue";
import {computed, useCssModule} from "vue";

const props = defineProps({
    setActive: Function,
    active: Boolean
})

const style = useCssModule();
const popupWrapperClasses = computed(() => {
    if (props.active) {
        return [style.categoryPopup, style.popupaAtive]
    }
    return style.categoryPopup
})
</script>

<style module>
@import "PopupSearchMobileComponent.module.scss";
</style>

// resources/js/components/Popups/PopupSearchMobileComponent.jsx
import React, {useEffect, useState} from 'react';
import classes from "./PopupSearchMobileComponent.module.scss";
import InputHeaderSearchComponent from "../UI/Inputs/InputHeaderSearchComponent";


const PopupSearchMobileComponent = ({classWrapper = null, setActive, active}) => {

    const [popupWrapperClasses, setPopupWrapperClasses] = useState([classes.categoryPopup, classWrapper]);


    useEffect(() => {
        if (active && !popupWrapperClasses.find((item) => item === classes.popupaAtive)) {
            document.body.style.overflow = "hidden";
            setPopupWrapperClasses([...popupWrapperClasses, classes.popupaAtive]);
        } else if (!active && popupWrapperClasses.find((item) => item === classes.popupaAtive)) {
            document.body.style.overflow = "auto";
            setPopupWrapperClasses([...popupWrapperClasses.filter((item) => item !== classes.popupaAtive)]);
        }
    }, [active])

    return (
        <div className={popupWrapperClasses.join(" ")} onClick={() => setActive(false)}>
            <div className={classes.body} onClick={(e) => e.stopPropagation()}>
                <div className={classes.backButton} onClick={() => setActive(false)}>назад</div>
                <InputHeaderSearchComponent containerPropClass={classes.searchContainer}/>
            </div>
        </div>
    );
};

export default PopupSearchMobileComponent;
