// resources/js/components/Content/Product/ProductCommentComponent.jsx
import React from 'react';
import classes from "./ProductCommentComponent.module.scss";
import {Link} from "react-router-dom";
import StarsRatingComponent from "../../UI/Raiting/StarsRatingComponent.vue";
import {AiOutlineDislike, AiOutlineLike} from "react-icons/ai";

const ProductCommentComponent = () => {
    return (
        <div className={classes.commentWrapper}>
            <div className={classes.commentHeader}>
                <Link className={classes.userLink}>
                    <div className={classes.userImage}>
                        <img
                            src="https://avatars.mds.yandex.net/i?id=fcd934fb3fd86beedd13a150df698436402c5590-5113868-images-thumbs&n=13"/>
                    </div>
                    <div className={classes.userName}>Oleg</div>
                </Link>
                <div className={classes.userScore}>
                    <StarsRatingComponent startRating={3}/>
                    <span className={classes.commentDate}>2 Декабря 2022</span>
                </div>

            </div>
            <div className={classes.commentBody}>
                <div className={classes.commentInfoBlock}>
                    <div className={classes.commentInfoBlockTitle}>Достоинства:</div>
                    <div>цена</div>
                </div>
                <div className={classes.commentInfoBlock}>
                    <div className={classes.commentInfoBlockTitle}>Недостатки:</div>
                    <div>Придумайте</div>
                </div>
                <div className={classes.commentInfoBlock}>
                    <div className={classes.commentInfoBlockTitle}>Комментарий:</div>
                    <div>Норм</div>
                </div>
            </div>
            <div className={classes.commentFooter}>
                <div className={classes.commentActions}>
                    <div>Отзыв полезен?</div>
                    <div className={classes.commentActionsButtons}>
                        <button className={classes.commentActionsButton}><AiOutlineDislike
                            className={classes.buttonIcon}/><span>1</span></button>
                        <button className={classes.commentActionsButton}><AiOutlineLike className={classes.buttonIcon}/><span>2</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ProductCommentComponent;

// resources/js/components/Content/Product/ProductCommentComponent.vue
<template>
    <div :class="$style.commentWrapper">
        <div :class="$style.commentHeader">
            <router-link to="#" :class="$style.userLink">
                <div :class="$style.userImage">
                    <img
                        src="https://avatars.mds.yandex.net/i?id=fcd934fb3fd86beedd13a150df698436402c5590-5113868-images-thumbs&n=13"/>
                </div>
                <div :class="$style.userName">Oleg</div>
            </router-link>
            <div :class="$style.userScore">
                <StarsRatingComponent :start-rating="3"/>
                    <span :class="$style.commentDate">2 Декабря 2022</span>
            </div>

        </div>
        <div :class="$style.commentBody">
            <div :class="$style.commentInfoBlock">
                <div :class="$style.commentInfoBlockTitle">Достоинства:</div>
                <div>цена</div>
            </div>
            <div :class="$style.commentInfoBlock">
                <div :class="$style.commentInfoBlockTitle">Недостатки:</div>
                <div>Придумайте</div>
            </div>
            <div :class="$style.commentInfoBlock">
                <div :class="$style.commentInfoBlockTitle">Комментарий:</div>
                <div>Норм</div>
            </div>
        </div>
        <div :class="$style.commentFooter">
            <div :class="$style.commentActions">
                <div>Отзыв полезен?</div>
                <div :class="$style.commentActionsButtons">
                    <button :class="$style.commentActionsButton">
                        <font-awesome-icon icon="fa-regular fa-thumbs-down" :class="$style.buttonIcon"/>
                        <span>1</span></button>
                    <button :class="$style.commentActionsButton">
                        <font-awesome-icon icon="fa-regular fa-thumbs-up" :class="$style.buttonIcon"/>
                        <span>2</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>

import StarsRatingComponent from "../../UI/Raiting/StarsRatingComponent.vue";
</script>

<style module>
@import "ProductCommentComponent.module.scss";
</style>
