// resources/js/components/UI/Inputs/InputHeaderSearchComponent.jsx
import React from 'react';
import classes from "./InputHeaderSearchComponent.module.scss"
import {HiSearch} from "react-icons/hi";

const InputHeaderSearchComponent = ({children = null, containerPropClass, ...props}) => {
    return (
        <form className={[classes.headerSearchContainer, containerPropClass].filter(Boolean).join(" ")}>
                <input {...props} className={classes.searchInput} type="text" name="#" placeholder={children}/>
                <button className={classes.button} onClick={(event) => {event.preventDefault()}}><HiSearch className={classes.buttonIcon}/>
                </button>
        </form>
    );
};

export default InputHeaderSearchComponent;

// resources/js/components/UI/Inputs/InputHeaderSearchComponent.vue
<template>
    <form :class="[$style.headerSearchContainer, containerPropClass]">
        <input :class="$style.searchInput" type="text" name="#" :placeholder="placeholder"/>
        <button :class="$style.button" @click.prevent>
            <font-awesome-icon :class="$style.buttonIcon" icon="fa-solid fa-magnifying-glass"/>
        </button>
    </form>
</template>

<script>
export default {
    props:['placeholder', 'containerPropClass']
}
</script>

<style module>
@import "InputHeaderSearchComponent.module.scss";
</style>
