// resources/js/components/UI/Inputs/InputPasswordFormComponent.vue
<template>
    <div :class="$style.inputPasswordContainer">
        <input :type="inputType ? 'text' : 'password'" v-bind="$attrs" :value="modelValue" @input="updateValue" :class="$style.input"/>
        <button type="button" :class="$style.button" @click="setInputType">
            <font-awesome-icon icon="fa-regular fa-eye" v-if="inputType" :class="$style.buttonIcon"/>
            <font-awesome-icon icon="fa-regular fa-eye-slash" v-else :class="$style.buttonIcon"/>
        </button>
    </div>
</template>

<script setup>
import {ref} from "vue";

const inputType = ref(false)
function  setInputType(){
    inputType.value = !inputType.value;
}

const props = defineProps({
    modelValue: String
})

const emit = defineEmits(['update:modelValue'])

const updateValue = (event) => {
    emit('update:modelValue', event.target.value)
}

</script>

<style module>
@import "InputPasswordFormComponent.module.scss";
@import "InputFormComponent.module.scss";
</style>

// resources/js/components/UI/Inputs/InputPasswordFormComponent.jsx
import React, {useState} from 'react';
import classes from "./InputPasswordFormComponent.module.scss";
import {BsEye, BsEyeSlash} from "react-icons/bs";

const InputPasswordFormComponent = ({
                                        inputPropClass = null,
                                        placeholderText = "что-то...",
                                        ...props
                                    }) => {
    const [inputType, setInputType] = useState(false);
    return (
        <div className={classes.inputPasswordContainer}>
            <input type={inputType ? "text" : "password"}
                   className={[classes.input, inputPropClass].filter(item => item).join(" ")}
                   placeholder={placeholderText} {...props}/>
            <button className={classes.button} onClick={() => setInputType(!inputType)}>
                {inputType ? <BsEye className={classes.buttonIcon}/> :
                    <BsEyeSlash className={classes.buttonIcon}/>}
            </button>
        </div>
    );
};

export default InputPasswordFormComponent;
