// resources/js/components/Content/Authentication/SignUpComponent.jsx
import React, {useState} from 'react';
import classes from "./AuthentificationForm.module.scss";
import InputTextFormComponent from "../../UI/Inputs/InputTextFormComponent";
import InputPasswordFormComponent from "../../UI/Inputs/InputPasswordFormComponent";
import ButtonComponent from "../../UI/Buttons/ButtonComponent.vue";
import CheckboxComponent from "../../UI/Checkboxes/CheckboxComponent";
import useSignUp from "../../../hooks/AuthHooks/useSignUp";

const SignUpComponent = () => {

    const [signUpData, setSignUpData] = useState({
        email: "",
        password: "",
        password_confirmation: "",
        remember: false
    });
    const [errors, setErrors] = useState(null)

    const signUp = useSignUp(setErrors);

    return (
        <>
            <div className={classes.formRow}>
                <span className={classes.formRowTitle}>Введите email</span>
                <InputTextFormComponent value={signUpData?.email}
                                        onChange={(e) => setSignUpData({
                                            ...signUpData,
                                            email: e.target.value

                                        })} inputPropClass={classes.inputForm}/>
                {errors?.email && <div className={classes.errorField}>{errors.email[0]}</div>}
            </div>
            <div className={classes.formRow}>
                <span className={classes.formRowTitle}>Введите пароль</span>
                <InputPasswordFormComponent value={signUpData?.password}
                                            onChange={(e) => setSignUpData({
                                                ...signUpData,
                                                password: e.target.value

                                            })} inputPropClass={classes.inputForm}/>
                {errors?.password && <div className={classes.errorField}>{errors.password[0]}</div>}
            </div>
            <div className={classes.formRow}>
                <span className={classes.formRowTitle}>Повторите пароль</span>
                <InputPasswordFormComponent
                    value={signUpData?.password_confirmation}
                    onChange={(e) => setSignUpData({
                        ...signUpData,
                        password_confirmation: e.target.value

                    })} inputPropClass={classes.inputForm}/>
            </div>
            <div className={classes.formRow}>
                <CheckboxComponent title={"Запомнить меня"} id={"remember_me"}
                                   onChange={(e) => setSignUpData({...signUpData, remember: !signUpData.remember})
                                   }/>

            </div>
            <ButtonComponent onClick={() => signUp(signUpData)}
                             classWrapper={classes.buttonForm}>Регистрация</ButtonComponent>
        </>
    );
};

export default SignUpComponent;

// resources/js/components/Content/Authentication/SignUpComponent.vue
<template>
    <div :class="$style.formRow">
        <span :class="$style.formRowTitle">Введите email</span>
        <InputTextFormComponent v-model="signUpData.email" :class="$style.inputForm"/>
        <div v-if="errors?.email" :class="$style.errorField">{{ errors.email[0] }}</div>
    </div>
    <div :class="$style.formRow">
        <span :class="$style.formRowTitle">Введите пароль</span>
        <InputPasswordFormComponent v-model="signUpData.password" :class="$style.inputForm"/>
        <div v-if="errors?.password" :class="$style.errorField">{{ errors.password[0] }}</div>
    </div>
    <div :class="$style.formRow">
        <span :class="$style.formRowTitle">Повторите пароль</span>
        <InputPasswordFormComponent v-model="signUpData.password_confirmation" :class="$style.inputForm"/>
    </div>
    <div :class="$style.formRow">
        <CheckboxBoolComponent id="remember_me" v-model="signUpData.remember" :value="true">
            Запомнить меня
        </CheckboxBoolComponent>
    </div>
    <ButtonComponent
        @click="signUp(signUpData)"
        :class="$style.buttonForm">Зарегистрироватся
    </ButtonComponent>
</template>

<script setup>
import ButtonComponent from "../../UI/Buttons/ButtonComponent.vue";
import {reactive, ref} from "vue";
import CheckboxBoolComponent from "../../UI/Checkboxes/CheckboxBoolComponent.vue";
import useSignUp from "../../../hooks/AuthHooks/useSignUp.js";
import InputTextFormComponent from "../../UI/Inputs/InputTextFormComponent.vue";
import InputPasswordFormComponent from "../../UI/Inputs/InputPasswordFormComponent.vue";

const signUpData = reactive({
    email: "",
    password: "",
    password_confirmation: "",
    remember: false
})
const errors = ref(null);
const signUp = useSignUp(errors);
</script>

<style module>
@import "AuthentificationForm.module.scss";
</style>
