// resources/js/components/Content/Authentication/SignInComponent.vue
<template>
    <div :class="$style.formRow">
        <span :class="$style.formRowTitle">Введите email</span>
        <InputTextFormComponent v-model="signInData.email" :class="$style.inputForm"/>
        <div v-if="errors?.email" :class="$style.errorField">{{ errors.email[0] }}</div>
    </div>
    <div :class="$style.formRow">
        <span :class="$style.formRowTitle">Введите пароль</span>
        <InputPasswordFormComponent v-model="signInData.password" :class="$style.inputForm"/>
        <div v-if="errors?.password" :class="$style.errorField">{{ errors.password[0] }}</div>
    </div>
    <div :class="$style.formRow">
        <CheckboxBoolComponent v-model="signInData.remember" id="remember_me" :value="true">
            Запомнить меня
        </CheckboxBoolComponent>
    </div>
    <ButtonComponent :class="$style.buttonForm" @click="signIn(signInData)">
        Войти
    </ButtonComponent>
</template>

<script setup>
import ButtonComponent from "../../UI/Buttons/ButtonComponent.vue";
import {reactive, ref} from "vue";
import CheckboxBoolComponent from "../../UI/Checkboxes/CheckboxBoolComponent.vue";
import useSignIn from "../../../hooks/AuthHooks/useSignIn.js";
import InputPasswordFormComponent from "../../UI/Inputs/InputPasswordFormComponent.vue";
import InputTextFormComponent from "../../UI/Inputs/InputTextFormComponent.vue";

const signInData = reactive({email: "", password: "", remember: false})
const errors = ref(null)
const signIn = useSignIn(errors);
</script>

<style module>
@import "AuthentificationForm.module.scss";
</style>

// resources/js/components/Content/Authentication/SignInComponent.jsx
import React, {useState} from 'react';
import classes from "./AuthentificationForm.module.scss";
import InputTextFormComponent from "../../UI/Inputs/InputTextFormComponent";
import InputPasswordFormComponent from "../../UI/Inputs/InputPasswordFormComponent";
import ButtonComponent from "../../UI/Buttons/ButtonComponent.vue";
import CheckboxComponent from "../../UI/Checkboxes/CheckboxComponent";
import useSignIn from "../../../hooks/AuthHooks/useSignIn";

const SignInComponent = () => {

        const [signInData, setSignInData] = useState({email: "", password: "", remember: false});
        const [errors, setErrors] = useState(null);
        const signIn = useSignIn(setErrors);

    return (
            <>
                <div className={classes.formRow}>
                    <span className={classes.formRowTitle}>Введите email</span>
                    <InputTextFormComponent value={signInData?.email}
                                            onChange={(e) => setSignInData({
                                                ...signInData,
                                                email: e.target.value
                                            })} inputPropClass={classes.inputForm}/>
                    {
                        errors?.email && <div className={classes.errorField}>{errors.email[0]}</div>
                    }
                </div>
                <div className={classes.formRow}>
                    <span className={classes.formRowTitle}>Введите пароль</span>
                    <InputPasswordFormComponent value={signInData?.password}
                                                onChange={(e) => setSignInData({
                                                    ...signInData,
                                                    password: e.target.value
                                                })} inputPropClass={classes.inputForm}/>
                    {
                        errors?.password && <div className={classes.errorField}>{errors.password[0]}</div>
                    }
                </div>
                <div className={classes.formRow}>
                    <CheckboxComponent title="Запомнить меня" id="remember_me"
                                       onChange={(e) => setSignInData({...signInData, remember: !signInData.remember})
                                  }/>

                </div>
                <ButtonComponent onClick={() => signIn(signInData)}
                                 classWrapper={classes.buttonForm}>Войти</ButtonComponent>
            </>
        );
    }
;

export default SignInComponent;
