// resources/js/components/UI/Counter/CounterComponent.jsx
import React, {useEffect, useState} from 'react';
import classes from "./CounterComponent.module.scss";
import {AiOutlineMinus, AiOutlinePlus} from "react-icons/ai";
import useBasketChangeQuantity from "../../../hooks/BasketHooks/useBasketChangeQuantity";

const CounterComponent = ({product, initialQuantity}) => {
    const [inputValue, setInputValue] = useState(initialQuantity);
    const changeQuantity = useBasketChangeQuantity();
    useEffect(() => {
        setInputValue(initialQuantity);
    }, [initialQuantity])

    function inputChange(length) {
        if (Number(length) < 1000) {
            setInputValue(Number(length));
        }
    }

    function saveChangeAfterFocusOut(length) {
        if (Number(length) === 0) {
            setInputValue(1);
            length = 1;
        }
        changeQuantity(product, length);
    }

    function inputIncrement(length) {
        length = Number(length) + 1;
        if (length < 1000) {
            setInputValue(length);
            changeQuantity(product, length);
        }
    }

    function inputDecrement(length) {
        length = Number(length) - 1;
        if (length > 0) {
            setInputValue(length);
            changeQuantity(product, length);
        }
    }

    return (
        <div className={classes.counter}>
            <button className={classes.addSubtract} onClick={() => inputDecrement(inputValue)}><AiOutlineMinus
                className={classes.buttonIcon}/></button>
            <input type={"text"} onBlur={(e) => saveChangeAfterFocusOut(e.target.value)}
                   onChange={event => inputChange(event.target.value)} value={inputValue} className={classes.input}/>
            <button className={classes.addButton} onClick={() => inputIncrement(inputValue)}><AiOutlinePlus
                className={classes.buttonIcon}/></button>
        </div>
    );
};

export default CounterComponent;

// resources/js/components/UI/Counter/CounterComponent.vue
<template>
    <div :class="$style.counter">
        <button :class="$style.addSubtract" @click="inputDecrement(inputValue)">
            <font-awesome-icon icon="fa-solid fa-minus" :class="$style.buttonIcon"/>
        </button>
        <input type="text" v-model="inputValue" @input="inputChange" @blur="saveChangeAfterFocusOut"
               :class="$style.input"/>
        <button :class="$style.addButton" @click="inputIncrement(inputValue)">
            <font-awesome-icon icon="fa-solid fa-plus" :class="$style.buttonIcon"/>
        </button>
    </div>
</template>

<script setup>

import {ref} from "vue";
import {useStore} from "vuex";
import useBasketChangeQuantity from "../../../hooks/BasketHooks/useBasketChangeQuantity.js";

const props = defineProps({
    initialQuantity: {
        type: Number,
        required: true
    },
    product: {
        required: true
    }
});

const inputValue = ref(props.initialQuantity);
const store = useStore();
const changeQuantity = useBasketChangeQuantity();

function inputChange(e) {
    inputValue.value = Number(e.target.value.replace(/[^0-9]/g, ""));
}

function saveChangeAfterFocusOut(e) {
    let value = Number(e.target.value.replace(/[^0-9]/g, ""))
    if (Number(value) === 0) {
        value = 1
    }
    inputValue.value = value;
    changeQuantity(props.product, inputValue.value);
}

function inputIncrement(count) {
    count = Number(count) + 1;
    if (count < 1000) {
        inputValue.value = (count);
        changeQuantity(props.product, inputValue.value);
    }
}

function inputDecrement(count) {
    count = Number(count) - 1;
    if (count > 0) {
        inputValue.value = count;
        changeQuantity(props.product, inputValue.value);
    }
}


</script>

<style module>
@import "CounterComponent.module.scss";
</style>
