// resources/js/components/UI/Selects/CatalogSorterBlockComponent.jsx
import React, {useEffect, useState} from 'react';
import {GoSettings} from "react-icons/go";
import {useSearchParams} from "react-router-dom";
import classes from "./CatalogSorterBlockComponent.module.scss"

const CatalogSorterBlockComponent = ({setCatalogMobileActive}) => {

    const [isLoad, setIsLoad] = useState(true);
    const [sorterData, setSorterData] = useState([]);
    const [searchParams, setSearchParams] = useSearchParams();

    useEffect(() => {
        axios.get('/api/sorter-data').then(response => {
            setSorterData(Object.entries(response.data))
            setIsLoad(false)
        })
            .catch(error => {
                console.log(error);
            })
    }, []);

    function changeSelect(event) {
        setSearchParams((prevSearchParams) => {
            let value = event.target.value;
            prevSearchParams.set('sort', value);
            return prevSearchParams;
        });
    }

    return (
        <div className={classes.catalogSorter}>
            {
                !isLoad ?
                    <select className={classes.catalogSelect} defaultValue={searchParams.get('sort')}
                            onChange={changeSelect}>
                        <option hidden>Сортировка</option>
                        {
                            sorterData.map(([key, item]) =>
                                <option value={key}
                                        key={key}>{item}</option>)
                        }
                    </select>
                    : null
            }

            <GoSettings className={classes.catalogBurgerMobile} onClick={() => setCatalogMobileActive(true)}/>
        </div>
    );
};

export default CatalogSorterBlockComponent;

// resources/js/components/UI/Selects/CatalogSorterBlockComponent.vue
<template>
    <div :class="$style.catalogSorter" v-if="isLoaded">
        <select v-model="sortCurrValue" @change="changeSort" :class="$style.catalogSelect">
            <option hidden value="">Сортировка</option>
            <option v-for="[key, item] in sorterData"
                    :value="key"
                    :key="key"
            >
                {{ item }}
            </option>
        </select>
        <font-awesome-icon icon="fa-solid fa-sliders" :class="$style.catalogBurgerMobile"/>
        <!--        <GoSettings :class="$style.catalogBurgerMobile" onClick={() => setCatalogMobileActive(true)}/>-->
    </div>
</template>
<script setup>
import {computed, onMounted, ref} from "vue";
import {useRoute, useRouter} from "vue-router";

const isLoaded = ref(false);
const sorterData = ref([]);
const sortCurrValue = ref("");
const route = useRoute();
const router = useRouter();
const queryParams = computed(() => route.query);

const changeSort = (e) => {
    let resultQueryParams = {...queryParams.value, sort: e.target.value};
    router.push({query: resultQueryParams});
}

onMounted(() => {
    axios.get('/api/sorter-data').then(response => {
        sorterData.value = Object.entries(response.data);
        if (sorterData.value.some(([i, k]) => i === route.query.sort)) {
            sortCurrValue.value = route.query.sort;
        }
        isLoaded.value = true;
    })
        .catch(error => {
            console.log(error);
        })
})
</script>

<style module>
@import "CatalogSorterBlockComponent.module.scss";
</style>
